# Generated by Django 4.2.6 on 2023-10-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category'),
        ('store', '0002_offer_tag_alter_product_options_product_availability_and_more'),
    ]

    operations = [
    ]
