# Generated by Django 4.2.6 on 2023-11-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_category_options_alter_orders_options_and_more'),
        ('store', '0011_reviews_author'),
    ]

    operations = [
    ]
