# Generated by Django 4.2.6 on 2023-11-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_reviews_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_view',
            field=models.BooleanField(default=False, verbose_name='Is_view'),
        ),
    ]
