# Generated by Django 4.2.6 on 2023-11-03 19:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('store', '0011_reviews_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_index'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(max_length=150, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_type',
            field=models.CharField(default='pickup', max_length=100, verbose_name='Тип доставки'),
        ),
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='store.product'),
        ),
        migrations.AddField(
            model_name='orders',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authorization.profile'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='Orders',
        ),
    ]
