# Generated by Django 4.2.6 on 2023-11-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_images_product_preview_product_is_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='archived',
            field=models.BooleanField(default=True, verbose_name='Архивация'),
        ),
    ]
