# Generated by Django 4.2.6 on 2023-11-23 13:26

from django.db import migrations, models
import store.utils


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_orders_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.JSONField(default=store.utils.jsonfield_default_description, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.JSONField(default=store.utils.jsonfield_default_feature, verbose_name='Характеристика'),
        ),
    ]
