# Generated by Django 4.2.6 on 2023-11-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_orders_options_remove_product_is_view_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
