# Generated by Django 4.2.6 on 2023-11-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_description_alter_product_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
