# Generated by Django 4.2.6 on 2023-12-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_total_orders_total_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.ManyToManyField(related_name='categories', to='store.discount', verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='discount',
            name='priority',
            field=models.BooleanField(default=False, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='discount',
            name='sum_cart',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма корзины'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status_exception',
            field=models.TextField(blank=True, null=True, verbose_name='Статус ошибки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, 'Оплачено'), (2, 'Не оплачено'), (3, 'Доставляется')], verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость заказа'),
        ),
    ]
