# Generated by Django 4.2.6 on 2023-12-09 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_alter_profile_avatar_alter_profile_phone'),
        ('store', '0019_rename_total_orders_total_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(max_length=150, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status_exception',
            field=models.TextField(blank=True, null=True, verbose_name='Статус ошибки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='authorization.profile'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, 'Оплачено'), (2, 'Не оплачено'), (3, 'Доставляется')], verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость заказа'),
        ),
    ]
