# Generated by Django 4.2.6 on 2023-12-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_orders_archived'),
        ('store', '0022_discount_image_discount_slug_discount_title_and_more'),
    ]

    operations = [
    ]
