# Generated by Django 4.2.6 on 2023-12-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_merge_20231218_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивация'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=150, unique=True),
        ),
    ]
