# Generated by Django 4.2.6 on 2023-12-09 21:59

import authorization.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_profile_phone_profile_slug_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=authorization.models.profile_images_directory_path, verbose_name='Фотография товара'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Teleфон'),
        ),
    ]
