# Generated by Django 4.2.6 on 2023-12-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_profile_archived_alter_profile_name_store'),
        ('authorization', '0006_alter_profile_avatar'),
    ]

    operations = [
    ]
