# Generated by Django 4.2.6 on 2023-12-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_merge_20231218_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивация'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_store',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя магазина'),
        ),
    ]
