# Generated by Django 4.2.6 on 2024-01-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0002_electrocharacteristic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractcharacteristicmodel',
            options={'ordering': ['id'], 'verbose_name': 'Абстрактные характеристики', 'verbose_name_plural': 'Абстрактные характеристики'},
        ),
        migrations.AlterModelOptions(
            name='electrocharacteristic',
            options={'ordering': ['id'], 'verbose_name': 'Характеристики электроники', 'verbose_name_plural': 'Характеристики электроники'},
        ),
        migrations.AlterModelOptions(
            name='headphonescharacteristic',
            options={'ordering': ['id'], 'verbose_name': 'Характеристики наушников', 'verbose_name_plural': 'Характеристики наушников'},
        ),
        migrations.AlterModelOptions(
            name='kitchencharacteristic',
            options={'ordering': ['id'], 'verbose_name': 'Характеристики кухонной техники', 'verbose_name_plural': 'Характеристики кухонной техники'},
        ),
        migrations.AlterModelOptions(
            name='microwaveovencharacteristic',
            options={'ordering': ['id'], 'verbose_name': 'Характеристики микроволновой печи', 'verbose_name_plural': 'Характеристики микроволновых печей'},
        ),
        migrations.AlterModelOptions(
            name='mobilecharacteristic',
            options={'ordering': ['id'], 'verbose_name': 'Характеристики телефона', 'verbose_name_plural': 'Характеристики телефонов'},
        ),
        migrations.AlterModelOptions(
            name='notebookcharacteristic',
            options={'ordering': ['id'], 'verbose_name': 'Характеристики ноутбука', 'verbose_name_plural': 'Характеристики ноутбуков'},
        ),
        migrations.AlterModelOptions(
            name='photocamcharacteristic',
            options={'ordering': ['id'], 'verbose_name': 'Характеристики фотоаппарата', 'verbose_name_plural': 'Характеристики фотоаппаратов'},
        ),
        migrations.AlterModelOptions(
            name='torcherecharacteristic',
            options={'ordering': ['id'], 'verbose_name': 'Характеристики торшера', 'verbose_name_plural': 'Характеристики торшеров'},
        ),
        migrations.AlterModelOptions(
            name='tvsetcharacteristic',
            options={'ordering': ['id'], 'verbose_name': 'Характеристики телевизора', 'verbose_name_plural': 'Характеристики телевизоров'},
        ),
        migrations.AlterModelOptions(
            name='washmachinecharacteristic',
            options={'ordering': ['id'], 'verbose_name': 'Характеристики стиральной машины', 'verbose_name_plural': 'Характеристики стиральных машин'},
        ),
    ]
