# Generated by Django 4.2.6 on 2024-01-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_alter_abstractcharacteristicmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractcharacteristicmodel',
            name='color_en',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='abstractcharacteristicmodel',
            name='color_ru',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='abstractcharacteristicmodel',
            name='made_in_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Сделан в '),
        ),
        migrations.AddField(
            model_name='abstractcharacteristicmodel',
            name='made_in_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Сделан в '),
        ),
        migrations.AddField(
            model_name='electrocharacteristic',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AddField(
            model_name='electrocharacteristic',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AddField(
            model_name='electrocharacteristic',
            name='type_product_en',
            field=models.CharField(default='Информации нет', max_length=20, null=True, verbose_name='Тип электроники'),
        ),
        migrations.AddField(
            model_name='electrocharacteristic',
            name='type_product_ru',
            field=models.CharField(default='Информации нет', max_length=20, null=True, verbose_name='Тип электроники'),
        ),
        migrations.AddField(
            model_name='headphonescharacteristic',
            name='bluetooth_en',
            field=models.CharField(default='Нет', max_length=20, null=True, verbose_name='Наличие Bluetooth'),
        ),
        migrations.AddField(
            model_name='headphonescharacteristic',
            name='bluetooth_ru',
            field=models.CharField(default='Нет', max_length=20, null=True, verbose_name='Наличие Bluetooth'),
        ),
        migrations.AddField(
            model_name='headphonescharacteristic',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AddField(
            model_name='headphonescharacteristic',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AddField(
            model_name='headphonescharacteristic',
            name='fit_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Как носить'),
        ),
        migrations.AddField(
            model_name='headphonescharacteristic',
            name='fit_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Как носить'),
        ),
        migrations.AddField(
            model_name='headphonescharacteristic',
            name='hdmi_en',
            field=models.CharField(default='Нет', max_length=20, null=True, verbose_name='HDMI'),
        ),
        migrations.AddField(
            model_name='headphonescharacteristic',
            name='hdmi_ru',
            field=models.CharField(default='Нет', max_length=20, null=True, verbose_name='HDMI'),
        ),
        migrations.AddField(
            model_name='headphonescharacteristic',
            name='mic_en',
            field=models.CharField(default='Нет', max_length=20, null=True, verbose_name='Микрофон'),
        ),
        migrations.AddField(
            model_name='headphonescharacteristic',
            name='mic_ru',
            field=models.CharField(default='Нет', max_length=20, null=True, verbose_name='Микрофон'),
        ),
        migrations.AddField(
            model_name='headphonescharacteristic',
            name='wireless_en',
            field=models.CharField(default='Нет', max_length=20, null=True, verbose_name='Беспроводные'),
        ),
        migrations.AddField(
            model_name='headphonescharacteristic',
            name='wireless_ru',
            field=models.CharField(default='Нет', max_length=20, null=True, verbose_name='Беспроводные'),
        ),
        migrations.AddField(
            model_name='kitchencharacteristic',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AddField(
            model_name='kitchencharacteristic',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AddField(
            model_name='kitchencharacteristic',
            name='type_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип техники'),
        ),
        migrations.AddField(
            model_name='kitchencharacteristic',
            name='type_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип техники'),
        ),
        migrations.AddField(
            model_name='microwaveovencharacteristic',
            name='grill_en',
            field=models.CharField(default='Информации нет', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='microwaveovencharacteristic',
            name='grill_ru',
            field=models.CharField(default='Информации нет', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mobilecharacteristic',
            name='phone_type_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Тип мобильного телефона'),
        ),
        migrations.AddField(
            model_name='mobilecharacteristic',
            name='phone_type_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Тип мобильного телефона'),
        ),
        migrations.AddField(
            model_name='notebookcharacteristic',
            name='laptop_type_en',
            field=models.CharField(default='Информации нет', max_length=20, null=True, verbose_name='Тип ноутбука'),
        ),
        migrations.AddField(
            model_name='notebookcharacteristic',
            name='laptop_type_ru',
            field=models.CharField(default='Информации нет', max_length=20, null=True, verbose_name='Тип ноутбука'),
        ),
        migrations.AddField(
            model_name='photocamcharacteristic',
            name='type_en',
            field=models.CharField(default='Информации нет', max_length=30, null=True, verbose_name='Тип фотоаппарата'),
        ),
        migrations.AddField(
            model_name='photocamcharacteristic',
            name='type_ru',
            field=models.CharField(default='Информации нет', max_length=30, null=True, verbose_name='Тип фотоаппарата'),
        ),
        migrations.AddField(
            model_name='torcherecharacteristic',
            name='led_type_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип лампочки'),
        ),
        migrations.AddField(
            model_name='torcherecharacteristic',
            name='led_type_ru',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип лампочки'),
        ),
        migrations.AddField(
            model_name='torcherecharacteristic',
            name='place_type_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Место расположения'),
        ),
        migrations.AddField(
            model_name='torcherecharacteristic',
            name='place_type_ru',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Место расположения'),
        ),
        migrations.AddField(
            model_name='tvsetcharacteristic',
            name='country_en',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Страна производитель'),
        ),
        migrations.AddField(
            model_name='tvsetcharacteristic',
            name='country_ru',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Страна производитель'),
        ),
        migrations.AddField(
            model_name='tvsetcharacteristic',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AddField(
            model_name='tvsetcharacteristic',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AddField(
            model_name='tvsetcharacteristic',
            name='hdmi_en',
            field=models.CharField(default='Нет', max_length=20, null=True, verbose_name='HDMI'),
        ),
        migrations.AddField(
            model_name='tvsetcharacteristic',
            name='hdmi_ru',
            field=models.CharField(default='Нет', max_length=20, null=True, verbose_name='HDMI'),
        ),
        migrations.AddField(
            model_name='tvsetcharacteristic',
            name='name_en',
            field=models.TextField(blank=True, default='TVSet', null=True),
        ),
        migrations.AddField(
            model_name='tvsetcharacteristic',
            name='name_ru',
            field=models.TextField(blank=True, default='TVSet', null=True),
        ),
        migrations.AddField(
            model_name='tvsetcharacteristic',
            name='wi_fi_en',
            field=models.CharField(default='Нет', max_length=20, null=True, verbose_name='Наличие Wi-Fi'),
        ),
        migrations.AddField(
            model_name='tvsetcharacteristic',
            name='wi_fi_ru',
            field=models.CharField(default='Нет', max_length=20, null=True, verbose_name='Наличие Wi-Fi'),
        ),
        migrations.AddField(
            model_name='washmachinecharacteristic',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AddField(
            model_name='washmachinecharacteristic',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительное описание'),
        ),
        migrations.AddField(
            model_name='washmachinecharacteristic',
            name='type_loading_en',
            field=models.CharField(default='Информации нет', max_length=20, null=True, verbose_name='Тип загрузки'),
        ),
        migrations.AddField(
            model_name='washmachinecharacteristic',
            name='type_loading_ru',
            field=models.CharField(default='Информации нет', max_length=20, null=True, verbose_name='Тип загрузки'),
        ),
    ]
